name: Groundwater Data Scraper

on:
  schedule:
    - cron: '*/4 * * * *'
  workflow_dispatch:

jobs:
  scrape-groundwater:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Groundwater Function
        run: |
          curl -X POST 'https://glcbkolaazmzzfbxfvxd.supabase.co/functions/v1/get_groundwater' \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json" \
          --data '{}'

      
      - name: Scheduled run completed
        run: echo "âœ… Groundwater function executed at $(date)"


